name: Deploy Java & DB
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          echo "🚀 Java 배포 시작..."
          
          # 1. 프로젝트 폴더로 이동 (모든 작업은 여기서 합니다)
          cd ~/deploy/repo-vessel
          
          # 2. 최신 코드 받기
          git pull origin main

          # 3. .env 파일 생성 (폴더 안에서 만들어야 도커가 읽음)
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" > .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env          
          echo "DB_USER=${{ secrets.DB_ID }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_URL=jdbc:mariadb://vms-db:3306/vms_db" >> .env
          # 형식: jdbc:mariadb://[컨테이너이름]:3306/[DB이름]
        

          # 4. 도커 실행 (이제 같은 폴더에 docker-compose.yml이 있으니 실행됨)
          docker compose up -d --build vessel-monitoring-system-WAS vms-db
          
          echo "✅ Java & DB 배포 완료!"
