name: Deploy Java & DB
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: #run 수동 버튼 생성

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Java 배포 (SSH Remote Commands)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_NAME }}
        key: ${{ secrets.SERVER_ACCESS_KEY }}
        # 깃허브에 저장한 비밀번호를 이 스크립트로 넘겨줌
        envs: DB_URL, DB_USERNAME, DB_PASSWORD
        script: |
          echo "🚀 Java 배포 시작..."
          
          # 1. 기존 소스 삭제 및 재다운로드
          sudo rm -rf /home/ubuntu/deploy/repo-vessel || true
          cd /home/ubuntu/deploy
          git clone -b main https://github.com/newri0807/vessel-system.git repo-vessel
          
          # 2. 파일 생성 위치를 'Dockerfile'이 참조하는 곳으로 지정
          # Dockerfile이 'COPY WebContent ./WebContent'를 하므로 그 구조에 맞춰야 함
          cd /home/ubuntu/deploy/repo-vessel
          
          # 폴더 생성 (WebContent와 같은 레벨 또는 src 내부에 생성)
          mkdir -p src/main/resources/resources
          
          # 변수 값 주입 (쌍따옴표 필수)
          echo "db.driverClassName=com.mysql.jdbc.Driver"" > src/main/resources/resources/database.properties
          echo "db.url=${DB_URL}" >> src/main/resources/resources/database.properties
          echo "db.username=${DB_USERNAME}" >> src/main/resources/resources/database.properties
          echo "db.password=${DB_PASSWORD}" >> src/main/resources/resources/database.properties
          
          echo "🔎 생성된 파일 내용 확인 (보안 주의):"
          cat src/main/resources/resources/database.properties
          
          # 3. 도커 실행
          cd /home/ubuntu/deploy
          docker compose up -d --build vessel-system

